name: simple_weather
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  image_network: ^2.5.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
